// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDInMvSnCo7Q4cEW2ba-JnFGjjkREPkH8o',
    appId: '1:595280279262:web:bfbf5b46543a97ace3f44f',
    messagingSenderId: '595280279262',
    projectId: 'questra-sleeplove',
    authDomain: 'questra-sleeplove.firebaseapp.com',
    databaseURL: 'https://questra-sleeplove-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'questra-sleeplove.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvtA22Rk7Dylb-XO-pRhkRkg_N6JG7KOc',
    appId: '1:595280279262:android:195474caef669d66e3f44f',
    messagingSenderId: '595280279262',
    projectId: 'questra-sleeplove',
    databaseURL: 'https://questra-sleeplove-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'questra-sleeplove.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgx9oc3b3jy4WuFSSrn5f75wyz178j_ow',
    appId: '1:595280279262:ios:987108ac053ea197e3f44f',
    messagingSenderId: '595280279262',
    projectId: 'questra-sleeplove',
    databaseURL: 'https://questra-sleeplove-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'questra-sleeplove.firebasestorage.app',
    iosClientId: '595280279262-r5r053hpor349rktqldfv0krfji7bv82.apps.googleusercontent.com',
    iosBundleId: 'com.questra.sleeplove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgx9oc3b3jy4WuFSSrn5f75wyz178j_ow',
    appId: '1:595280279262:ios:987108ac053ea197e3f44f',
    messagingSenderId: '595280279262',
    projectId: 'questra-sleeplove',
    databaseURL: 'https://questra-sleeplove-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'questra-sleeplove.firebasestorage.app',
    iosClientId: '595280279262-r5r053hpor349rktqldfv0krfji7bv82.apps.googleusercontent.com',
    iosBundleId: 'com.questra.sleeplove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDInMvSnCo7Q4cEW2ba-JnFGjjkREPkH8o',
    appId: '1:595280279262:web:d8845cb4117f22a0e3f44f',
    messagingSenderId: '595280279262',
    projectId: 'questra-sleeplove',
    authDomain: 'questra-sleeplove.firebaseapp.com',
    databaseURL: 'https://questra-sleeplove-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'questra-sleeplove.firebasestorage.app',
  );
}
